### ISSUE TITLE
Some structurally recursive operator definitions cause failures with `smt`

### ISSUE THREAD

**Issue by oskgo** [EasyCrypt/easycrypt#334]
This is related to #62 and #144. Moving the conversation started in https://github.com/EasyCrypt/easycrypt/issues/62#issuecomment-1422526340 since this is a different issue (https://github.com/EasyCrypt/easycrypt/issues/62#issuecomment-1422800786)

The following fails with `Ident Top_baz is not yet declared`:
```
type nat = [O | S of nat].

op g: nat -> (nat -> nat) -> nat.

op baz (n: nat) (m: nat): nat = 
  with n = O    => O
  with n = S n' => g m (baz n').

lemma test n m: baz n = baz m.
proof.
smt().
```

**Comment by oskgo** [comment]
@strub, can you reopen this?

**Comment by strub** [comment]
I cannot reproduce in `main`. Are you sure you are up to date (or that the fix has been merged in the branch you are using)?

**Comment by strub** [comment]
Sorry, was using the initial test.

**Comment by oskgo** [comment]
I should mention that with your fix it seems to be pretty easy to work around this bug by using the recursive call as an explicit argument to the inline function instead of having it be part of its definition. It's definitely lower priority than before.

A bug is still a bug though.
